name: time_range_selector_widget
# description: This is a time range selector package.

description: |
  Easily select time range.

  Key Features:
  - Intuitive drag-and-select interface.
  - Customizable appearance and styling to match your app's design.
  - Suitable for use cases like calendar apps, scheduling, and more.
  - Supports setting minimum and maximum selectable time ranges.
  - Seamless integration with your existing Flutter projects.

version: 0.0.2
repository: https://github.com/SHAJED99/time_range_selector_widget
license: BSD 3-Clause

screenshots:
  - description: 'Example of time_range_selector_widget'
    path: screenshots/1.gif


topics:
  - time-range
  - time
  - time-selector


environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
